# Generated by Django 3.2.15 on 2023-08-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='tb_polls',
        ),
    ]
