# Generated by Django 3.2.15 on 2023-08-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
    ]
